config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  #Users
  match '/users',     to: 'users#index',   via: 'get'
  match '/users/:id', to: 'users#show',    via: 'get'

  resources :users, :only =>[:show, :edit, :update]

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: "users/registrations"
        }, :path_prefix => 'd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, :except =>[:new]
  end

  resources :communities do
    resources :stories do
      resources :storycomments, :except =>[:new]
    end
    member do
      post 'add_membership'
      delete 'remove_membership'
    end
  end

  resources :feedbacks, only: [:index, :new, :create]

end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_many :storycomments, dependent: :destroy
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

    #index
    def index
      # @stories = Story.all
      # @communities = Community.all
      @community = Community.find(params[:community_id])
      redirect_to community_path(@community)
    end

    #show
    def show
      @story = Story.find(params[:id])
      @storycomment = Storycomment.new
    end

    #edit
    def edit
      @community = Community.find(params[:community_id])
      @story = Story.find(params[:id])
      if current_user == @story.user || current_user.id == 1
      else
        redirect_to community_story_path(@story)
        flash[:alert] = "Only the author of the story can edit it!"
      end
    end

    #update
    def update
      @community = Community.find(params[:community_id])
      @story = Story.find(params[:id])
      @story.update(story_params.merge(user:current_user))
      redirect_to community_story_path(@community, @story)
    end

    #new
    def new
      @community = Community.find(params[:community_id])
      if current_user
        if @community.memberships.find_by(user_id: current_user.id)
          @story = Story.new
        else
          redirect_to community_path(@community)
        end
      else
        redirect_to community_path(@community)
      end
    end

    #create
    def create
      @community = Community.find(params[:community_id])
      @story = @community.stories.create!(story_params.merge(user: current_user))
      redirect_to community_story_path(@community, @story)
    end

    #destroy
    def destroy
      @community = Community.find(params[:community_id])
      @story = Story.find(params[:id])
      if current_user == @story.user || current_user.id == 1
        @story.destroy
      else
        flash[:alert] = "Only the author of the story can delete it"
      end
      redirect_to community_path(@community)
    end

    private
    def story_params
      params.require(:story).permit(:title, :content, :image)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/edit.html.erb
<div class="element">
<h2 class="title">Edit Story</h2>

<%= form_for [@community, @story] do |f| %>
  <p><%= f.label :title %><br />
    <br />
  <%= f.text_field :title, :size=>"80" %></p>
  <br />

  <p><%= f.label :image %><br />
    <br />
  <%= f.text_field :image, :size=>"80" %></p>
    <br />

  <p><%= f.label :content %><br />
    <br />
  <%= f.text_field :content, :size=>"80" %></p>
  <br />

  <br />
  <p class="submit"><%= f.submit %></p>
<% end %>
</div>

app/views/stories/new.html.erb
<div class="element">
<h2 class="title">Add A New Story To This Community</h2>

<%= form_for [@community, @story] do |f| %>
  <p><%= f.label :title %><br />
    <br />
  <%= f.text_field :title, :size=>"80" %></p>
  <br />

  <p><%= f.label :image %><br />
    <br />
  <%= f.text_field :image, :size=>"80" %></p>
    <br />

  <p><%= f.label :content %><br />
    <br />
  <%= f.text_field :content, :size=>"80" %></p>
  <br />

  <br />
  <p class="submit"><%= f.submit %></p>
<% end %>
</div>

app/views/stories/show.html.erb
<div class="element">
<h2 class="title"><%= @story.title %> </h2>
<h2 class="title">Community: <%= link_to  @story.community.name, community_path(@story.community_id) %> </h2>
<img class="image" src="<%= @story.image %>" alt="Story Image" title="Story Image"><br />
<img class="userImage" src="<%= @story.user.image %>" alt="User Image" title="User Image">
<h4>By: <%= @story.user.name %></h4>
<h4>Created At: <%= @story.created_at %>, Last Update: <%= @story.updated_at %></h4>
<hr />
<p> <%= @story.content %> </p>
<% if current_user %>
  <% if current_user == @story.user || current_user.id == 1 %>
    <br />
    <% @community = Community.find(params[:community_id]) %>
    <%= link_to "Edit Story", edit_community_story_path(@community, @story) %> |
    <%= link_to "Delete Story", community_story_path(@community, @story), method: :delete %>
  <% end %>
<% end %>

</div>

<div class="element barrier">
  <h3>Comments</h3>
  <br />
</div>

<% @story.storycomments.each do |storycomment| %>
  <div class="comment">
    <img class="userImage" src="<%= storycomment.user.image %>" alt="User Image" title="User Image">
    <h4>By: <%= storycomment.user.name %></h4>
    <h4>Created At: <%= storycomment.created_at %>, Last Update <%= storycomment.updated_at %></h4>
    <hr />
    <p><%= storycomment.content %></p>
    <% if current_user %>
      <% if current_user == storycomment.user || current_user.id == 1 %>
        <br />
        <% @community = Community.find(params[:community_id]) %>
        <%= link_to "Edit", edit_community_story_storycomment_path(@community, @story, storycomment) %> |
        <%= link_to "Delete", community_story_storycomment_path(@community, @story, storycomment), method: :delete %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if current_user %>
  <div class="comment">
    <h4>Add A New Comment</h4>
    <br />
    <% @community = Community.find(params[:community_id]) %>
    <%= form_for [@community, @story, @storycomment] do |f| %>
      <p>
      <%= f.text_field :content, :size=>"80" %></p>
      <br />
      <p class="submit"><%= f.submit %></p>
    <% end %>
  </div>
<% end %>