config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  #Users
  match '/users',     to: 'users#index',   via: 'get'
  match '/users/:id', to: 'users#show',    via: 'get'

  resources :users, :only =>[:show, :edit, :update]

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: "users/registrations"
        }, :path_prefix => 'd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, :except =>[:new]
  end

  resources :communities do
    resources :stories do
      resources :storycomments, :except =>[:new]
    end
    member do
      post 'add_membership'
      delete 'remove_membership'
    end
  end

  resources :feedbacks, only: [:index, :new, :create]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #index
  def index
  @communities = Community.all
    if current_user
      @posts = Post.all
    else
    end
  end

  #show
  def show
    if current_user
      @post = Post.find(params[:id])
      @comment = Comment.new
    else
      redirect_to root_path
    end
  end

  #edit
  def edit
    @post = Post.find(params[:id])
    if current_user == @post.user || current_user.id == 1
    else
      redirect_to post_path(@post)
      flash[:alert] = "Only the author of the post can edit it!"
    end
  end

  #update
  def update
    @post = Post.find(params[:id])
    @post.update(post_params.merge(user:current_user))
    redirect_to post_path(@post)
  end

  #new
  def new
    if current_user
      @post = Post.new
    else
      redirect_to root_path
    end
  end

  #create
  def create
    @post = Post.create!(post_params.merge(user: current_user))
    redirect_to post_path(@post)
  end

  #destroy
  def destroy
    @post = Post.find(params[:id])
    if current_user == @post.user || current_user.id == 1
      @post.destroy
    else
      flash[:alert] = "Only the author of the post can delete"
    end
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="element">
<h2 class="title">Edit: <%= @post.title %></h2>

<%= form_for @post do |f| %>
  <p><%= f.label :title %><br />
    <br />
  <%= f.text_field :title, :size=>"80" %></p>
  <br />

  <p><%= f.label :image %><br />
    <br />
  <%= f.text_field :image, :size=>"80" %></p>
    <br />

  <p><%= f.label :content %><br />
    <br />
  <%= f.text_field :content, :size=>"80" %></p>
  <br />

  <br />
  <p class="submit"><%= f.submit %></p>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="element barrier">
  <h2>Tell The World Your Story!<br /> <br />You story belongs here!</h2>
</div>

<% if current_user %>
  <div class="element barrier">
    <h2>Posts From Members</h2>
  </div>
<% end %>

<% if current_user %>
  <% @posts.each do |post| %>
    <div class="element">
      <h2 class="title"><%= link_to post.title, post_path(post) %></h2>
      <img class="image" src="<%= post.image %>" alt="Story Image" title="Story Image"><br />
      <img class="userImage" src="<%= post.user.image %>" alt="User Image" title="User Image">
      <% if current_user %>
        <h3>By: <%= link_to post.user.name, user_path(post.user)%></h3>
      <% else %>
        <h3>By: <%= post.user.name %></h3>
      <% end %>
      <h4>Created At: <%= post.created_at %>, Last Update: <%= post.updated_at %></h4>
      <hr />
      <p> <%= post.content %> </p>
    </div>
  <% end %>
<% end %>

<div class="element barrier">
  <h2>Posts From Communities</h2>
</div>

<% @communities.each do |community| %>
  <% community.stories.each do |story| %>
    <div class="element">
      <h2 class="title"><%= link_to story.title, community_path(story) %></h2>
      <img class="image" src="<%= story.image %>" alt="Story Image" title="Story Image"><br />
      <img class="userImage" src="<%= story.user.image %>" alt="User Image" title="User Image">
      <h3>By: <%= story.user.name %></h3>
      <h4>Created At: <%= story.created_at %>, Last Update: <%= story.updated_at %></h4>
      <hr />
      <p> <%= story.content %> </p>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="element">
<h2 class="title">Add A New Story</h2>

<%= form_for @post do |f| %>
  <p><%= f.label :title %><br />
    <br />
  <%= f.text_field :title, :size=>"80" %></p>
  <br />

  <p><%= f.label :image %><br />
    <br />
  <%= f.text_field :image, :size=>"80" %></p>
    <br />

  <p><%= f.label :content %><br />
    <br />
  <%= f.text_field :content, :size=>"80" %></p>
  <br />

  <br />
  <p class="submit"><%= f.submit %></p>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="element">
<h2 class="title"><%= @post.title %> </h2>
<img class="image" src="<%= @post.image %>" alt="Story Image" title="Story Image"><br />
<img class="userImage" src="<%= @post.user.image %>" alt="User Image" title="User Image">
<h4>By: <%= @post.user.name %></h4>
<h4>Created At: <%= @post.created_at %>, Last Update: <%= @post.updated_at %></h4>
<hr />
<p> <%= @post.content %> </p>
<% if current_user %>
  <% if current_user == @post.user || current_user.id == 1%>
  <br />
  <%= link_to "Edit Post", edit_post_path(@post) %> |
  <%= link_to "Delete Post", post_path(@post), method: :delete %>
  <% end %>
<% end %>
</div>

<div class="element barrier">
  <h3>Comments</h3>
  <br />
</div>

<% @post.comments.each do |comment| %>
  <div class="comment">
    <img class="userImage" src="<%= comment.user.image %>" alt="User Image" title="User Image">
    <h4>By: <%= comment.user.name %></h4>
    <h4>Created At: <%= comment.created_at %>, Last Update <%= comment.updated_at %></h4>
    <hr />
    <p><%= comment.content %></p>
    <% if current_user %>
      <% if current_user == comment.user || current_user.id == 1%>
        <br />
        <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
        <%= link_to "Delete", post_comment_path(@post, comment), method: :delete %>
        <% end %>
      <% end %>
  </div>
<% end %>


<% if current_user %>
  <div class="comment">
    <h4>Add A New Comment</h4>
    <br />
    <%= form_for [@post, @comment] do |f| %>
      <p>
      <%= f.text_field :content, :size=>"80" %></p>
      <br />

      <p class="submit"><%= f.submit %></p>
    <% end %>
  </div>
<% end %>