config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  #Users
  match '/users',     to: 'users#index',   via: 'get'
  match '/users/:id', to: 'users#show',    via: 'get'

  resources :users, :only =>[:show, :edit, :update]

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: "users/registrations"
        }, :path_prefix => 'd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, :except =>[:new]
  end

  resources :communities do
    resources :stories do
      resources :storycomments, :except =>[:new]
    end
    member do
      post 'add_membership'
      delete 'remove_membership'
    end
  end

  resources :feedbacks, only: [:index, :new, :create]

end

app/models/community.rb
class Community < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  has_many :stories, dependent: :destroy
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  #index
  def index
    @communities = Community.all
  end

  #show
  def show
    @community = Community.find(params[:id])
  end

  #edit
  def edit
    @community = Community.find(params[:id])
    if current_user
      if current_user.id == 1
      else
        redirect_to community_path(@community)
        flash[:alert] = "Only admins can edit communities!"
      end
    else
      redirect_to community_path(@community)
    end
  end

  #update
  def update
    @community = Community.find(params[:id])
    @community.update(community_params)
    redirect_to community_path(@community)
  end

  #new
  def new
    @community = Community.new
  end

  #create
  def create
    @community = Community.create!(community_params)
    redirect_to community_path(@community)
  end

  #destroy
  def destroy
    @community = Community.find(params[:id])
    @community.destroy
    redirect_to communities_path
  end

  #Join Community
  def add_membership
    @community = Community.find(params[:id])
    @community.memberships.create!(user_id: current_user.id)
    redirect_to :back
  end

  #Leave Community
  def remove_membership
    @community = Community.find(params[:id])
    @user = current_user
    Membership.find_by(community_id: @community.id, user_id: @user.id).destroy
    redirect_to :back
  end

  private
  def community_params
    params.require(:community).permit(:name, :header)
  end


end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/edit.html.erb
<div class="element">
<h2 class="title">Edit Community</h2>

<%= form_for @community do |f| %>
  <p><%= f.label :name %><br />
    <br />
  <%= f.text_field :name, :size=>"80" %></p>
  <br />

  <p><%= f.label :header %><br />
    <br />
  <%= f.text_field :header, :size=>"80" %></p>
    <br />

  <p class="submit"><%= f.submit %></p>
<% end %>
  <br />
<%= link_to "Delete Community", community_path(@community), method: :delete %>

</div>

app/views/communities/index.html.erb
<% if current_user %>
  <div class="element barrier">
  <h2><%= link_to "Create A New Community", new_community_path %></h2>
  </div>
<% end %>

<% @communities.each do |community| %>
  <div class="element">
    <h2 class="title"><%= link_to community.name, community_path(community) %>
      <% if current_user %> |
        <% if current_user.id == 1 %>
          <%= link_to "Edit Community", edit_community_path(community) %> |
        <% end %>
        <% if community.memberships.find_by(user_id: current_user.id) %>
            <%= link_to "Leave Community".html_safe, remove_membership_community_path(community), method: :delete, class: "fav" %>
          <% else %>
            <%= link_to "Join Community".html_safe, add_membership_community_path(community), method: :post, class: "no-fav" %>
        <% end %>
      <% else %>
      <% end %>
    </h2>
    <img class="image" src="<%= community.header %>" alt="Community Image" title="Community Image"><br />
  </div>
<% end %>

app/views/communities/new.html.erb
<div class="element">
  <h2 class="title">Create A New Community</h2>

  <%= form_for @community do |f| %>
    <p><%= f.label :name %><br />
      <br />
    <%= f.text_field :name, :size=>"80" %></p>
    <br />

    <p><%= f.label :header %><br />
      <br />
    <%= f.text_field :header, :size=>"80" %></p>
      <br />

    <p class="submit"><%= f.submit %></p>
  <% end %>

</div>

app/views/communities/show.html.erb
<div class="element barrier">
<h2>Community: <%= @community.name %>
  <% if current_user %>
    <% if current_user.id == 1 %>
      | <%= link_to "Edit Community", edit_community_path %>
    <% end %>
  <% else %>
  <% end %>
</h2>
  <% if current_user %>
    <% if @community.memberships.find_by(user_id: current_user.id) %>
      <p><%= link_to "Add Story To This Community", new_community_story_path(@community) %></p>
      <% else %>
    <% end %>
  <% end %>
</div>

<img class="header" src="<%= @community.header %>"  alt="Community Image" title="Community Image"/>

<% if current_user %>
  <div class="members">
    <h4>Members:
    <% @community.memberships.each do |membership| %>
        <% @user = User.find(membership.user_id) %>
        <%= @user.name %>,
    <% end %>
  </h4>
  <p>
    <% if @community.memberships.find_by(user_id: current_user.id) %>
        <%= link_to "Leave Community".html_safe, remove_membership_community_path(@community), method: :delete, class: "fav" %>
      <% else %>
        <%= link_to "Join Community".html_safe, add_membership_community_path(@community), method: :post, class: "no-fav" %>
    <% end %>
  </p>
  <br />
  </div>
<% end %>

<% @community.stories.each do |story| %>
  <div class="element">
    <h2 class="title"><%= link_to story.title, community_story_path(@community, story) %></h2>
    <img class="image" src="<%= story.image %>" alt="Story Image" title="Story Image"><br />
    <img class="userImage" src="<%= story.user.image %>" alt="User Image" title="User Image">
    <h4>By: <%= story.user.name %></h4>
    <h4>Created At: <%= story.created_at %>, Updated at: <%= story.updated_at %> </h4>
    <hr />
    <p> <%= story.content %> </p>
  </div>
<% end %>