config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  #Users
  match '/users',     to: 'users#index',   via: 'get'
  match '/users/:id', to: 'users#show',    via: 'get'

  resources :users, :only =>[:show, :edit, :update]

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: "users/registrations"
        }, :path_prefix => 'd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, :except =>[:new]
  end

  resources :communities do
    resources :stories do
      resources :storycomments, :except =>[:new]
    end
    member do
      post 'add_membership'
      delete 'remove_membership'
    end
  end

  resources :feedbacks, only: [:index, :new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zxx">
  <head>
    <title>Storyteller</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
    <ul>
    <% if current_user %>
      <% if current_user.id == 1 %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Communities", communities_path %></li>
          <li><%= link_to "All Users", users_path %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Feedbacks", feedbacks_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Communities", communities_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
    <% else %>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Communities", communities_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
      <li><%= link_to "Register", new_user_registration_path %></li>
    <% end %>
    </ul>
  </nav>

  <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </main>

<footer>
  <p>
  Developed with &hearts; by Mike Nabil
  <% if current_user %>
    <%= link_to " (Give Feedback)", new_feedback_path %>
  <% end %>
  </p>
</footer>

  </body>
</html>